version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: uzivatel
      POSTGRES_DB: databaza
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint.initdb.d
    ports:
      - "5432:5432"

  web:
    image: nginx
    ports:
      - "80:80"

volumes:
  db-data: